name: Test CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install
        run: npm ci
      - name: Lint
        run: pnpm lint
      - name: Format
        run: pnpm format
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
